# Generated by Django 5.2.17 on 2026-09-04 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('legal_name', models.CharField(blank=True, help_text='For contracts/invoices; may differ from name.', max_length=255)),
                ('billing_email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('prospect', 'Prospect')], default='prospect', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('iswc', models.CharField(blank=True, db_index=True, help_text='Join key (ADR-01). Populated once registered.', max_length=32)),
                ('dmp_work_id', models.CharField(blank=True, db_index=True, help_text='Pointer into DMP (ADR-01) -- not a universal id RCMS owns.', max_length=64)),
                ('split_status', models.CharField(choices=[('draft', 'Draft'), ('complete', 'Complete'), ('registered', 'Registered')], default='draft', help_text='Gates CWR eligibility (ADR-02). Only RCMS domain logic may change this -- see Job.PATCH allow-list in serializers.py.', max_length=20)),
                ('cwr_registered', models.BooleanField(default=False, help_text='Cached flag; source of truth is DMP/society ACKs.')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(help_text='Owning customer.', on_delete=django.db.models.deletion.PROTECT, related_name='work_cases', to='core.company')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('cwr.musicmark', 'CWR - MusicMark'), ('ebr.musicmark', 'EBR - MusicMark'), ('cwr.mlc', 'CWR - MLC'), ('mlc.bulk', 'MLC Bulk'), ('mlc.claim', 'MLC Claim'), ('ack.import', 'ACK Import'), ('ack.ascap', 'ACK - ASCAP (child of cwr.musicmark)'), ('ack.bmi', 'ACK - BMI (child of cwr.musicmark)'), ('ack.socan', 'ACK - SOCAN (child of cwr.musicmark)'), ('ingest.dmp', 'Ingest - DMP'), ('distro.labelgrid', 'Distro - LabelGrid'), ('curve.ingest', 'Curve Ingest'), ('trolley.payout', 'Trolley Payout'), ('pro.manual', 'PRO Manual / Exception')], max_length=32)),
                ('destination', models.CharField(help_text='e.g. musicmark, dmp, labelgrid, curve, trolley.', max_length=64)),
                ('state', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('child_pending', 'Child Pending')], default='queued', max_length=20)),
                ('object_key', models.CharField(blank=True, help_text='MinIO key: rcms/{customer}/{job_id}/in|out/...', max_length=512)),
                ('checksum', models.CharField(blank=True, max_length=128)),
                ('n8n_run_id', models.CharField(blank=True, db_index=True, help_text='Set by n8n on pickup. Enables idempotent replay (ADR-12).', max_length=128)),
                ('external_ids', models.JSONField(blank=True, default=dict, help_text='Society/vendor-side IDs, e.g. MusicMark batch ref.')),
                ('error_text', models.TextField(blank=True)),
                ('idempotency_key', models.CharField(db_index=True, help_text='company_id + job_type + destination + industry_id_or_batch_id (ADR-12). Computed server-side -- see serializers.py.', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='core.company')),
                ('parent_job', models.ForeignKey(blank=True, help_text='Child ACK events point at their parent cwr.musicmark Job (ADR-03). A single per-society ACK closing does not close the parent batch.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_jobs', to='core.job')),
                ('work_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='core.workcase')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
